POST http://localhost/Proyectos/TPE-WEB-II/api/comments/songs/3
Content-Type: application/json

{
    "comment": "ooooooooooo",
    "score": 19
}

###

DELETE http://localhost/Proyectofrrs/TPE-WEB-II/api/comments/47

###

GET http://localhost/Proyectos/TPE-WEB-II/api/comments/songs/1/id/ASC

###

GET http://localhost/Proyectos/TPE-WEB-II/api/comments/songs/3/id/ASC